name: Java CI/CD with Maven and Fly.io

on:
    push:
        branches: [ master, main ]

    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout the repo
                uses: actions/checkout@v3

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'adopt'
                    cache: maven

            -   name: Build with Maven
                run: mvn clean package

            -   name: Deploy our Spring Boot app to fly.io
                uses: superfly/flyctl-actions/setup-flyctl@master
            -   run: flyctl deploy --remote-only
                env:
                    FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
